### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kenneth-dingga** [AsisRai/Facial-Recognition-System-to-Automatically-record-attendance-of-Coventry-University-Students#2]
this project has a bug

**Comment by AsisRai** [comment]
Sorry I was away. What's the bug you encountered?

**Comment by kenneth-dingga** [comment]
bug was if the person not register in system..when making attendance the
unregistered will recognize as the last registered person in DB

**Comment by kenneth-dingga** [comment]
the bug was in unregistered person will show as the last registered person
in attendane

**Comment by AsisRai** [comment]
I think you are right, I think I did forget to validate it. I was following the steps 1,2,3 and maybe that's why I didn't encounter the bug but a few lines of code should fix it. Thanks for letting me know.
